export const limitLabels: Record<string, string> = {
  max_produtos: "Máx. Produtos (-1 = ilimitado)",
  max_clientes: "Máx. Clientes (-1 = ilimitado)",
  max_pedidos_mes: "Máx. Pedidos/Mês (-1 = ilimitado)",
  max_armazenamento_mb: "Máx. Armazenamento (MB)",
  dashboard: "Dashboard",
  pedidos: "Pedidos",
  produtos: "Produtos",
  entregas: "Entregas",
  financeiro: "Financeiro",
  pdv_balcao: "PDV Balcão",
  pdv_mesas: "PDV Mesas + Comandas (Garçom)",
  enviar_whatsapp: "Enviar Pedido para o WhatsApp",
  enviar_painel: "Enviar Pedido para o Painel de Pedido",
  relatorios: "Relatórios Avançados",
  impressao_automatica: "Impressão Automática",
  impressao_duas_vias: "Imprimir Duas Vias",
  avaliacoes: "Avaliações de Pedidos",
  lembrete_aniversario: "Lembrete de Aniversariante",
  ranking_produtos: "Ranking de Produtos Mais Pedidos",
  graficos_vendas: "Gráficos de Vendas (Mais Detalhes)",
  cupons: "Cupons de Desconto",
  whatsapp: "WhatsApp Integrado",
  dominio: "Domínio Próprio",
  multi_lojas: "Multi-lojas",
  sem_branding: "Remover Branding (Powered by)",
  api: "Acesso à API",
};

export const defaultLimites = {
  max_produtos: 30,
  max_clientes: 100,
  max_pedidos_mes: 100,
  max_armazenamento_mb: 512,
  dashboard: true,
  pedidos: true,
  produtos: true,
  entregas: false,
  financeiro: false,
  pdv_balcao: false,
  pdv_mesas: false,
  enviar_whatsapp: true,
  enviar_painel: false,
  relatorios: false,
  impressao_automatica: false,
  impressao_duas_vias: false,
  avaliacoes: false,
  lembrete_aniversario: false,
  ranking_produtos: false,
  graficos_vendas: true,
  cupons: false,
  whatsapp: false,
  dominio: false,
  multi_lojas: false,
  sem_branding: false,
  api: false,
};
