ALTER TABLE public.lojas 
ADD COLUMN IF NOT EXISTS margem_esquerda INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS margem_direita INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS margem_superior INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS margem_inferior INTEGER DEFAULT 0;